name: build lazydocker
on:
  push:
    branches:
      - main
    paths:
      - lazydocker/lazydocker.spec
  workflow_dispatch:

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        uses: enflo/curl-action@master
        with:
          curl: >
            -X POST
            https://copr.fedorainfracloud.org/webhooks/custom/192871/7bf3c613-5906-4b97-afe3-d79aa232a7e7/lazydocker/
